/**
 * empty_backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Answer } from './answer';
import { Question } from './question';
import { QuestionAnswer } from './questionAnswer';


export interface GetResp { 
    answer: QuestionAnswer;
    answers: Array<Answer>;
    question: Question;
}

