/**
 * empty_backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: yy@yyue.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewQuestion } from './newQuestion';
import { NewAnswer } from './newAnswer';


export interface QuestionReq { 
    new_answers: Array<NewAnswer>;
    new_question: NewQuestion;
}

