/**
 * empty_backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Resource { 
    created_at: number;
    desc: string;
    icon: string;
    id: number;
    index: boolean;
    key: string;
    menu: boolean;
    name: string;
    path: string;
    resource_id: number;
    rtype: number;
    sort: number;
    updated_at: number;
}

