// source: proto/manage/sources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var gorm_options_gorm_pb = require('../../gorm/options/gorm_pb.js');
goog.object.extend(proto, gorm_options_gorm_pb);
var gorm_types_types_pb = require('../../gorm/types/types_pb.js');
goog.object.extend(proto, gorm_types_types_pb);
goog.exportSymbol('proto.manage.ListResponse', null, global);
goog.exportSymbol('proto.manage.SourcesItem', null, global);
goog.exportSymbol('proto.manage.SourcesItem.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.manage.SourcesItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.manage.SourcesItem.repeatedFields_, null);
};
goog.inherits(proto.manage.SourcesItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.manage.SourcesItem.displayName = 'proto.manage.SourcesItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.manage.ListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.manage.ListResponse.repeatedFields_, null);
};
goog.inherits(proto.manage.ListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.manage.ListResponse.displayName = 'proto.manage.ListResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.manage.SourcesItem.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.manage.SourcesItem.prototype.toObject = function(opt_includeInstance) {
  return proto.manage.SourcesItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.manage.SourcesItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manage.SourcesItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && gorm_types_types_pb.DeletedAt.toObject(includeInstance, f),
    sourcesItemid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    proto.manage.SourcesItem.toObject, includeInstance),
    key: jspb.Message.getFieldWithDefault(msg, 7, ""),
    type: jspb.Message.getFieldWithDefault(msg, 8, 0),
    index: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    path: jspb.Message.getFieldWithDefault(msg, 10, ""),
    name: jspb.Message.getFieldWithDefault(msg, 11, ""),
    menu: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    icon: jspb.Message.getFieldWithDefault(msg, 13, ""),
    desc: jspb.Message.getFieldWithDefault(msg, 14, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.manage.SourcesItem}
 */
proto.manage.SourcesItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.manage.SourcesItem;
  return proto.manage.SourcesItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.manage.SourcesItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.manage.SourcesItem}
 */
proto.manage.SourcesItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new gorm_types_types_pb.DeletedAt;
      reader.readMessage(value,gorm_types_types_pb.DeletedAt.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSourcesItemid(value);
      break;
    case 6:
      var value = new proto.manage.SourcesItem;
      reader.readMessage(value,proto.manage.SourcesItem.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 8:
      var value = /** @type {!proto.manage.SourcesItem.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIndex(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMenu(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setIcon(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setDesc(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.manage.SourcesItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.manage.SourcesItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.manage.SourcesItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manage.SourcesItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      gorm_types_types_pb.DeletedAt.serializeBinaryToWriter
    );
  }
  f = message.getSourcesItemid();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.manage.SourcesItem.serializeBinaryToWriter
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getIndex();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getMenu();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getIcon();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getDesc();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.manage.SourcesItem.Type = {
  ROUTE: 0,
  FUNCTION: 1,
  API: 2
};

/**
 * optional uint32 ID = 1;
 * @return {number}
 */
proto.manage.SourcesItem.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.manage.SourcesItem.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.manage.SourcesItem} returns this
*/
proto.manage.SourcesItem.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.manage.SourcesItem.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.manage.SourcesItem.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.manage.SourcesItem} returns this
*/
proto.manage.SourcesItem.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.manage.SourcesItem.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional types.DeletedAt deleted_at = 4;
 * @return {?proto.types.DeletedAt}
 */
proto.manage.SourcesItem.prototype.getDeletedAt = function() {
  return /** @type{?proto.types.DeletedAt} */ (
    jspb.Message.getWrapperField(this, gorm_types_types_pb.DeletedAt, 4));
};


/**
 * @param {?proto.types.DeletedAt|undefined} value
 * @return {!proto.manage.SourcesItem} returns this
*/
proto.manage.SourcesItem.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.manage.SourcesItem.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint32 sources_itemID = 5;
 * @return {number}
 */
proto.manage.SourcesItem.prototype.getSourcesItemid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setSourcesItemid = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated SourcesItem children = 6;
 * @return {!Array<!proto.manage.SourcesItem>}
 */
proto.manage.SourcesItem.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.manage.SourcesItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.manage.SourcesItem, 6));
};


/**
 * @param {!Array<!proto.manage.SourcesItem>} value
 * @return {!proto.manage.SourcesItem} returns this
*/
proto.manage.SourcesItem.prototype.setChildrenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.manage.SourcesItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.manage.SourcesItem}
 */
proto.manage.SourcesItem.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.manage.SourcesItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.clearChildrenList = function() {
  return this.setChildrenList([]);
};


/**
 * optional string key = 7;
 * @return {string}
 */
proto.manage.SourcesItem.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional Type type = 8;
 * @return {!proto.manage.SourcesItem.Type}
 */
proto.manage.SourcesItem.prototype.getType = function() {
  return /** @type {!proto.manage.SourcesItem.Type} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.manage.SourcesItem.Type} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional bool index = 9;
 * @return {boolean}
 */
proto.manage.SourcesItem.prototype.getIndex = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setIndex = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional string path = 10;
 * @return {string}
 */
proto.manage.SourcesItem.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string name = 11;
 * @return {string}
 */
proto.manage.SourcesItem.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional bool menu = 12;
 * @return {boolean}
 */
proto.manage.SourcesItem.prototype.getMenu = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setMenu = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional string icon = 13;
 * @return {string}
 */
proto.manage.SourcesItem.prototype.getIcon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setIcon = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string desc = 14;
 * @return {string}
 */
proto.manage.SourcesItem.prototype.getDesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.manage.SourcesItem} returns this
 */
proto.manage.SourcesItem.prototype.setDesc = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.manage.ListResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.manage.ListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.manage.ListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.manage.ListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manage.ListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    listList: jspb.Message.toObjectList(msg.getListList(),
    proto.manage.SourcesItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.manage.ListResponse}
 */
proto.manage.ListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.manage.ListResponse;
  return proto.manage.ListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.manage.ListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.manage.ListResponse}
 */
proto.manage.ListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.manage.SourcesItem;
      reader.readMessage(value,proto.manage.SourcesItem.deserializeBinaryFromReader);
      msg.addList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.manage.ListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.manage.ListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.manage.ListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.manage.ListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.manage.SourcesItem.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SourcesItem list = 1;
 * @return {!Array<!proto.manage.SourcesItem>}
 */
proto.manage.ListResponse.prototype.getListList = function() {
  return /** @type{!Array<!proto.manage.SourcesItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.manage.SourcesItem, 1));
};


/**
 * @param {!Array<!proto.manage.SourcesItem>} value
 * @return {!proto.manage.ListResponse} returns this
*/
proto.manage.ListResponse.prototype.setListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.manage.SourcesItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.manage.SourcesItem}
 */
proto.manage.ListResponse.prototype.addList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.manage.SourcesItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.manage.ListResponse} returns this
 */
proto.manage.ListResponse.prototype.clearListList = function() {
  return this.setListList([]);
};


goog.object.extend(exports, proto.manage);
