// source: user/oauth/v1/oauth.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var gorm_options_gorm_pb = require('../../../gorm/options/gorm_pb.js');
goog.object.extend(proto, gorm_options_gorm_pb);
var gorm_types_types_pb = require('../../../gorm/types/types_pb.js');
goog.object.extend(proto, gorm_types_types_pb);
goog.exportSymbol('proto.user.oauth.v1.OAuthClient', null, global);
goog.exportSymbol('proto.user.oauth.v1.OAuthToken', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.OAuthToken = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.OAuthToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.OAuthToken.displayName = 'proto.user.oauth.v1.OAuthToken';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.OAuthClient = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.OAuthClient, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.OAuthClient.displayName = 'proto.user.oauth.v1.OAuthClient';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.OAuthToken.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.OAuthToken.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.OAuthToken} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.OAuthToken.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && gorm_types_types_pb.DeletedAt.toObject(includeInstance, f),
    clientid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    redirecturi: jspb.Message.getFieldWithDefault(msg, 7, ""),
    scope: jspb.Message.getFieldWithDefault(msg, 8, ""),
    code: jspb.Message.getFieldWithDefault(msg, 9, ""),
    codeCreateAt: (f = msg.getCodeCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    codeExpiresIn: jspb.Message.getFieldWithDefault(msg, 11, 0),
    codeChallenge: jspb.Message.getFieldWithDefault(msg, 12, ""),
    codeChallengeMethod: jspb.Message.getFieldWithDefault(msg, 13, ""),
    access: jspb.Message.getFieldWithDefault(msg, 14, ""),
    accessCreateAt: (f = msg.getAccessCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    accessExpiresIn: jspb.Message.getFieldWithDefault(msg, 16, 0),
    refresh: jspb.Message.getFieldWithDefault(msg, 17, ""),
    refreshCreateAt: (f = msg.getRefreshCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    refreshExpiresIn: jspb.Message.getFieldWithDefault(msg, 19, 0),
    tokenType: jspb.Message.getFieldWithDefault(msg, 20, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.OAuthToken}
 */
proto.user.oauth.v1.OAuthToken.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.OAuthToken;
  return proto.user.oauth.v1.OAuthToken.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.OAuthToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.OAuthToken}
 */
proto.user.oauth.v1.OAuthToken.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new gorm_types_types_pb.DeletedAt;
      reader.readMessage(value,gorm_types_types_pb.DeletedAt.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirecturi(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setScope(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCodeCreateAt(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCodeExpiresIn(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodeChallenge(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodeChallengeMethod(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccess(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setAccessCreateAt(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAccessExpiresIn(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefresh(value);
      break;
    case 18:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setRefreshCreateAt(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRefreshExpiresIn(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setTokenType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.OAuthToken.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.OAuthToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.OAuthToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.OAuthToken.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      gorm_types_types_pb.DeletedAt.serializeBinaryToWriter
    );
  }
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRedirecturi();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getScope();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCodeCreateAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCodeExpiresIn();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getCodeChallenge();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getCodeChallengeMethod();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getAccess();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getAccessCreateAt();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAccessExpiresIn();
  if (f !== 0) {
    writer.writeInt64(
      16,
      f
    );
  }
  f = message.getRefresh();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getRefreshCreateAt();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRefreshExpiresIn();
  if (f !== 0) {
    writer.writeInt64(
      19,
      f
    );
  }
  f = message.getTokenType();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
};


/**
 * optional uint32 ID = 1;
 * @return {number}
 */
proto.user.oauth.v1.OAuthToken.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.OAuthToken.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
*/
proto.user.oauth.v1.OAuthToken.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthToken.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.OAuthToken.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
*/
proto.user.oauth.v1.OAuthToken.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthToken.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional types.DeletedAt deleted_at = 4;
 * @return {?proto.types.DeletedAt}
 */
proto.user.oauth.v1.OAuthToken.prototype.getDeletedAt = function() {
  return /** @type{?proto.types.DeletedAt} */ (
    jspb.Message.getWrapperField(this, gorm_types_types_pb.DeletedAt, 4));
};


/**
 * @param {?proto.types.DeletedAt|undefined} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
*/
proto.user.oauth.v1.OAuthToken.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthToken.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string clientID = 5;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setClientid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string userID = 6;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string redirectURI = 7;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getRedirecturi = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setRedirecturi = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string scope = 8;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getScope = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setScope = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string code = 9;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional google.protobuf.Timestamp code_create_at = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.OAuthToken.prototype.getCodeCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
*/
proto.user.oauth.v1.OAuthToken.prototype.setCodeCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.clearCodeCreateAt = function() {
  return this.setCodeCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthToken.prototype.hasCodeCreateAt = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int64 code_expires_in = 11;
 * @return {number}
 */
proto.user.oauth.v1.OAuthToken.prototype.getCodeExpiresIn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setCodeExpiresIn = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional string code_challenge = 12;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getCodeChallenge = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setCodeChallenge = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string code_challenge_method = 13;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getCodeChallengeMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setCodeChallengeMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string access = 14;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getAccess = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setAccess = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional google.protobuf.Timestamp access_create_at = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.OAuthToken.prototype.getAccessCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
*/
proto.user.oauth.v1.OAuthToken.prototype.setAccessCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.clearAccessCreateAt = function() {
  return this.setAccessCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthToken.prototype.hasAccessCreateAt = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional int64 access_expires_in = 16;
 * @return {number}
 */
proto.user.oauth.v1.OAuthToken.prototype.getAccessExpiresIn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setAccessExpiresIn = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional string refresh = 17;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getRefresh = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setRefresh = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional google.protobuf.Timestamp refresh_create_at = 18;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.OAuthToken.prototype.getRefreshCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 18));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
*/
proto.user.oauth.v1.OAuthToken.prototype.setRefreshCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.clearRefreshCreateAt = function() {
  return this.setRefreshCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthToken.prototype.hasRefreshCreateAt = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional int64 refresh_expires_in = 19;
 * @return {number}
 */
proto.user.oauth.v1.OAuthToken.prototype.getRefreshExpiresIn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setRefreshExpiresIn = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional string token_type = 20;
 * @return {string}
 */
proto.user.oauth.v1.OAuthToken.prototype.getTokenType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthToken} returns this
 */
proto.user.oauth.v1.OAuthToken.prototype.setTokenType = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.OAuthClient.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.OAuthClient.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.OAuthClient} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.OAuthClient.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && gorm_types_types_pb.DeletedAt.toObject(includeInstance, f),
    secret: jspb.Message.getFieldWithDefault(msg, 5, ""),
    domain: jspb.Message.getFieldWithDefault(msg, 6, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.OAuthClient}
 */
proto.user.oauth.v1.OAuthClient.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.OAuthClient;
  return proto.user.oauth.v1.OAuthClient.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.OAuthClient} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.OAuthClient}
 */
proto.user.oauth.v1.OAuthClient.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new gorm_types_types_pb.DeletedAt;
      reader.readMessage(value,gorm_types_types_pb.DeletedAt.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecret(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomain(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.OAuthClient.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.OAuthClient.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.OAuthClient} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.OAuthClient.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      gorm_types_types_pb.DeletedAt.serializeBinaryToWriter
    );
  }
  f = message.getSecret();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDomain();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional uint32 ID = 1;
 * @return {number}
 */
proto.user.oauth.v1.OAuthClient.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
 */
proto.user.oauth.v1.OAuthClient.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.OAuthClient.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
*/
proto.user.oauth.v1.OAuthClient.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
 */
proto.user.oauth.v1.OAuthClient.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthClient.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.OAuthClient.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
*/
proto.user.oauth.v1.OAuthClient.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
 */
proto.user.oauth.v1.OAuthClient.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthClient.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional types.DeletedAt deleted_at = 4;
 * @return {?proto.types.DeletedAt}
 */
proto.user.oauth.v1.OAuthClient.prototype.getDeletedAt = function() {
  return /** @type{?proto.types.DeletedAt} */ (
    jspb.Message.getWrapperField(this, gorm_types_types_pb.DeletedAt, 4));
};


/**
 * @param {?proto.types.DeletedAt|undefined} value
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
*/
proto.user.oauth.v1.OAuthClient.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
 */
proto.user.oauth.v1.OAuthClient.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.OAuthClient.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string secret = 5;
 * @return {string}
 */
proto.user.oauth.v1.OAuthClient.prototype.getSecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
 */
proto.user.oauth.v1.OAuthClient.prototype.setSecret = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string domain = 6;
 * @return {string}
 */
proto.user.oauth.v1.OAuthClient.prototype.getDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
 */
proto.user.oauth.v1.OAuthClient.prototype.setDomain = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string userID = 7;
 * @return {string}
 */
proto.user.oauth.v1.OAuthClient.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.OAuthClient} returns this
 */
proto.user.oauth.v1.OAuthClient.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


goog.object.extend(exports, proto.user.oauth.v1);
