// source: user/oauth/v1/oauth.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var gorm_options_gorm_pb = require('../../../gorm/options/gorm_pb.js');
goog.object.extend(proto, gorm_options_gorm_pb);
var gorm_types_types_pb = require('../../../gorm/types/types_pb.js');
goog.object.extend(proto, gorm_types_types_pb);
goog.exportSymbol('proto.user.oauth.v1.AuthorizeRequest', null, global);
goog.exportSymbol('proto.user.oauth.v1.AuthorizeResponse', null, global);
goog.exportSymbol('proto.user.oauth.v1.ClientStore', null, global);
goog.exportSymbol('proto.user.oauth.v1.CodeChallengeMethod', null, global);
goog.exportSymbol('proto.user.oauth.v1.GrantType', null, global);
goog.exportSymbol('proto.user.oauth.v1.ResponseType', null, global);
goog.exportSymbol('proto.user.oauth.v1.TokenGenerateRequest', null, global);
goog.exportSymbol('proto.user.oauth.v1.TokenInfo', null, global);
goog.exportSymbol('proto.user.oauth.v1.TokenRequest', null, global);
goog.exportSymbol('proto.user.oauth.v1.TokenResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.AuthorizeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.AuthorizeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.AuthorizeRequest.displayName = 'proto.user.oauth.v1.AuthorizeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.AuthorizeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.AuthorizeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.AuthorizeResponse.displayName = 'proto.user.oauth.v1.AuthorizeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.TokenRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.TokenRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.TokenRequest.displayName = 'proto.user.oauth.v1.TokenRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.TokenResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.TokenResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.TokenResponse.displayName = 'proto.user.oauth.v1.TokenResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.TokenInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.TokenInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.TokenInfo.displayName = 'proto.user.oauth.v1.TokenInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.ClientStore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.ClientStore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.ClientStore.displayName = 'proto.user.oauth.v1.ClientStore';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.user.oauth.v1.TokenGenerateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.user.oauth.v1.TokenGenerateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.user.oauth.v1.TokenGenerateRequest.displayName = 'proto.user.oauth.v1.TokenGenerateRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.AuthorizeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.AuthorizeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.AuthorizeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    redirecturi: jspb.Message.getFieldWithDefault(msg, 1, ""),
    responseType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    clientid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    scope: jspb.Message.getFieldWithDefault(msg, 4, ""),
    state: jspb.Message.getFieldWithDefault(msg, 5, ""),
    codeChallenge: jspb.Message.getFieldWithDefault(msg, 6, ""),
    codeChallengeMethod: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.AuthorizeRequest}
 */
proto.user.oauth.v1.AuthorizeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.AuthorizeRequest;
  return proto.user.oauth.v1.AuthorizeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.AuthorizeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.AuthorizeRequest}
 */
proto.user.oauth.v1.AuthorizeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirecturi(value);
      break;
    case 2:
      var value = /** @type {!proto.user.oauth.v1.ResponseType} */ (reader.readEnum());
      msg.setResponseType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setScope(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodeChallenge(value);
      break;
    case 7:
      var value = /** @type {!proto.user.oauth.v1.CodeChallengeMethod} */ (reader.readEnum());
      msg.setCodeChallengeMethod(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.AuthorizeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.AuthorizeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.AuthorizeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRedirecturi();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResponseType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getScope();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCodeChallenge();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCodeChallengeMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional string redirectURI = 1;
 * @return {string}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.getRedirecturi = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.AuthorizeRequest} returns this
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.setRedirecturi = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ResponseType response_type = 2;
 * @return {!proto.user.oauth.v1.ResponseType}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.getResponseType = function() {
  return /** @type {!proto.user.oauth.v1.ResponseType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.user.oauth.v1.ResponseType} value
 * @return {!proto.user.oauth.v1.AuthorizeRequest} returns this
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.setResponseType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string clientID = 3;
 * @return {string}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.AuthorizeRequest} returns this
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.setClientid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string scope = 4;
 * @return {string}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.getScope = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.AuthorizeRequest} returns this
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.setScope = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string state = 5;
 * @return {string}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.AuthorizeRequest} returns this
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string code_challenge = 6;
 * @return {string}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.getCodeChallenge = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.AuthorizeRequest} returns this
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.setCodeChallenge = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional CodeChallengeMethod code_challenge_method = 7;
 * @return {!proto.user.oauth.v1.CodeChallengeMethod}
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.getCodeChallengeMethod = function() {
  return /** @type {!proto.user.oauth.v1.CodeChallengeMethod} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.user.oauth.v1.CodeChallengeMethod} value
 * @return {!proto.user.oauth.v1.AuthorizeRequest} returns this
 */
proto.user.oauth.v1.AuthorizeRequest.prototype.setCodeChallengeMethod = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.AuthorizeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.AuthorizeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.AuthorizeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.AuthorizeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.AuthorizeResponse}
 */
proto.user.oauth.v1.AuthorizeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.AuthorizeResponse;
  return proto.user.oauth.v1.AuthorizeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.AuthorizeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.AuthorizeResponse}
 */
proto.user.oauth.v1.AuthorizeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.AuthorizeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.AuthorizeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.AuthorizeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.AuthorizeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.TokenRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.TokenRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.TokenRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.TokenRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    grantType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tokenGenerateRequest: (f = msg.getTokenGenerateRequest()) && proto.user.oauth.v1.TokenGenerateRequest.toObject(includeInstance, f),
    username: jspb.Message.getFieldWithDefault(msg, 3, ""),
    password: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.TokenRequest}
 */
proto.user.oauth.v1.TokenRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.TokenRequest;
  return proto.user.oauth.v1.TokenRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.TokenRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.TokenRequest}
 */
proto.user.oauth.v1.TokenRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.user.oauth.v1.GrantType} */ (reader.readEnum());
      msg.setGrantType(value);
      break;
    case 2:
      var value = new proto.user.oauth.v1.TokenGenerateRequest;
      reader.readMessage(value,proto.user.oauth.v1.TokenGenerateRequest.deserializeBinaryFromReader);
      msg.setTokenGenerateRequest(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.TokenRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.TokenRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.TokenRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.TokenRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGrantType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getTokenGenerateRequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.user.oauth.v1.TokenGenerateRequest.serializeBinaryToWriter
    );
  }
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional GrantType grant_type = 1;
 * @return {!proto.user.oauth.v1.GrantType}
 */
proto.user.oauth.v1.TokenRequest.prototype.getGrantType = function() {
  return /** @type {!proto.user.oauth.v1.GrantType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.user.oauth.v1.GrantType} value
 * @return {!proto.user.oauth.v1.TokenRequest} returns this
 */
proto.user.oauth.v1.TokenRequest.prototype.setGrantType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional TokenGenerateRequest token_generate_request = 2;
 * @return {?proto.user.oauth.v1.TokenGenerateRequest}
 */
proto.user.oauth.v1.TokenRequest.prototype.getTokenGenerateRequest = function() {
  return /** @type{?proto.user.oauth.v1.TokenGenerateRequest} */ (
    jspb.Message.getWrapperField(this, proto.user.oauth.v1.TokenGenerateRequest, 2));
};


/**
 * @param {?proto.user.oauth.v1.TokenGenerateRequest|undefined} value
 * @return {!proto.user.oauth.v1.TokenRequest} returns this
*/
proto.user.oauth.v1.TokenRequest.prototype.setTokenGenerateRequest = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.TokenRequest} returns this
 */
proto.user.oauth.v1.TokenRequest.prototype.clearTokenGenerateRequest = function() {
  return this.setTokenGenerateRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.TokenRequest.prototype.hasTokenGenerateRequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string username = 3;
 * @return {string}
 */
proto.user.oauth.v1.TokenRequest.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenRequest} returns this
 */
proto.user.oauth.v1.TokenRequest.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string password = 4;
 * @return {string}
 */
proto.user.oauth.v1.TokenRequest.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenRequest} returns this
 */
proto.user.oauth.v1.TokenRequest.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.TokenResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.TokenResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.TokenResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.TokenResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    tokenInfo: (f = msg.getTokenInfo()) && proto.user.oauth.v1.TokenInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.TokenResponse}
 */
proto.user.oauth.v1.TokenResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.TokenResponse;
  return proto.user.oauth.v1.TokenResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.TokenResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.TokenResponse}
 */
proto.user.oauth.v1.TokenResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.user.oauth.v1.TokenInfo;
      reader.readMessage(value,proto.user.oauth.v1.TokenInfo.deserializeBinaryFromReader);
      msg.setTokenInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.TokenResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.TokenResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.TokenResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.TokenResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTokenInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.user.oauth.v1.TokenInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional TokenInfo token_info = 1;
 * @return {?proto.user.oauth.v1.TokenInfo}
 */
proto.user.oauth.v1.TokenResponse.prototype.getTokenInfo = function() {
  return /** @type{?proto.user.oauth.v1.TokenInfo} */ (
    jspb.Message.getWrapperField(this, proto.user.oauth.v1.TokenInfo, 1));
};


/**
 * @param {?proto.user.oauth.v1.TokenInfo|undefined} value
 * @return {!proto.user.oauth.v1.TokenResponse} returns this
*/
proto.user.oauth.v1.TokenResponse.prototype.setTokenInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.TokenResponse} returns this
 */
proto.user.oauth.v1.TokenResponse.prototype.clearTokenInfo = function() {
  return this.setTokenInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.TokenResponse.prototype.hasTokenInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.TokenInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.TokenInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.TokenInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.TokenInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && gorm_types_types_pb.DeletedAt.toObject(includeInstance, f),
    clientid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    redirecturi: jspb.Message.getFieldWithDefault(msg, 7, ""),
    scope: jspb.Message.getFieldWithDefault(msg, 8, ""),
    code: jspb.Message.getFieldWithDefault(msg, 9, ""),
    codeCreateAt: (f = msg.getCodeCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    codeExpiresIn: jspb.Message.getFieldWithDefault(msg, 11, 0),
    codeChallenge: jspb.Message.getFieldWithDefault(msg, 12, ""),
    codeChallengeMethod: jspb.Message.getFieldWithDefault(msg, 13, 0),
    access: jspb.Message.getFieldWithDefault(msg, 14, ""),
    accessCreateAt: (f = msg.getAccessCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    accessExpiresIn: jspb.Message.getFieldWithDefault(msg, 16, 0),
    refresh: jspb.Message.getFieldWithDefault(msg, 17, ""),
    refreshCreateAt: (f = msg.getRefreshCreateAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    refreshExpiresIn: jspb.Message.getFieldWithDefault(msg, 19, 0),
    tokenType: jspb.Message.getFieldWithDefault(msg, 20, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.TokenInfo}
 */
proto.user.oauth.v1.TokenInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.TokenInfo;
  return proto.user.oauth.v1.TokenInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.TokenInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.TokenInfo}
 */
proto.user.oauth.v1.TokenInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new gorm_types_types_pb.DeletedAt;
      reader.readMessage(value,gorm_types_types_pb.DeletedAt.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirecturi(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setScope(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCodeCreateAt(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCodeExpiresIn(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodeChallenge(value);
      break;
    case 13:
      var value = /** @type {!proto.user.oauth.v1.CodeChallengeMethod} */ (reader.readEnum());
      msg.setCodeChallengeMethod(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccess(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setAccessCreateAt(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAccessExpiresIn(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefresh(value);
      break;
    case 18:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setRefreshCreateAt(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRefreshExpiresIn(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setTokenType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.TokenInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.TokenInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.TokenInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.TokenInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      gorm_types_types_pb.DeletedAt.serializeBinaryToWriter
    );
  }
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRedirecturi();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getScope();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCodeCreateAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCodeExpiresIn();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getCodeChallenge();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getCodeChallengeMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      13,
      f
    );
  }
  f = message.getAccess();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getAccessCreateAt();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAccessExpiresIn();
  if (f !== 0) {
    writer.writeInt64(
      16,
      f
    );
  }
  f = message.getRefresh();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getRefreshCreateAt();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRefreshExpiresIn();
  if (f !== 0) {
    writer.writeInt64(
      19,
      f
    );
  }
  f = message.getTokenType();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
};


/**
 * optional uint32 ID = 1;
 * @return {number}
 */
proto.user.oauth.v1.TokenInfo.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.TokenInfo.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
*/
proto.user.oauth.v1.TokenInfo.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.TokenInfo.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.TokenInfo.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
*/
proto.user.oauth.v1.TokenInfo.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.TokenInfo.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional types.DeletedAt deleted_at = 4;
 * @return {?proto.types.DeletedAt}
 */
proto.user.oauth.v1.TokenInfo.prototype.getDeletedAt = function() {
  return /** @type{?proto.types.DeletedAt} */ (
    jspb.Message.getWrapperField(this, gorm_types_types_pb.DeletedAt, 4));
};


/**
 * @param {?proto.types.DeletedAt|undefined} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
*/
proto.user.oauth.v1.TokenInfo.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.TokenInfo.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string clientID = 5;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setClientid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string userID = 6;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string redirectURI = 7;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getRedirecturi = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setRedirecturi = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string scope = 8;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getScope = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setScope = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string code = 9;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional google.protobuf.Timestamp code_create_at = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.TokenInfo.prototype.getCodeCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
*/
proto.user.oauth.v1.TokenInfo.prototype.setCodeCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.clearCodeCreateAt = function() {
  return this.setCodeCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.TokenInfo.prototype.hasCodeCreateAt = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int64 code_expires_in = 11;
 * @return {number}
 */
proto.user.oauth.v1.TokenInfo.prototype.getCodeExpiresIn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setCodeExpiresIn = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional string code_challenge = 12;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getCodeChallenge = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setCodeChallenge = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional CodeChallengeMethod code_challenge_method = 13;
 * @return {!proto.user.oauth.v1.CodeChallengeMethod}
 */
proto.user.oauth.v1.TokenInfo.prototype.getCodeChallengeMethod = function() {
  return /** @type {!proto.user.oauth.v1.CodeChallengeMethod} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {!proto.user.oauth.v1.CodeChallengeMethod} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setCodeChallengeMethod = function(value) {
  return jspb.Message.setProto3EnumField(this, 13, value);
};


/**
 * optional string access = 14;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getAccess = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setAccess = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional google.protobuf.Timestamp access_create_at = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.TokenInfo.prototype.getAccessCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
*/
proto.user.oauth.v1.TokenInfo.prototype.setAccessCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.clearAccessCreateAt = function() {
  return this.setAccessCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.TokenInfo.prototype.hasAccessCreateAt = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional int64 access_expires_in = 16;
 * @return {number}
 */
proto.user.oauth.v1.TokenInfo.prototype.getAccessExpiresIn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setAccessExpiresIn = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional string refresh = 17;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getRefresh = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setRefresh = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional google.protobuf.Timestamp refresh_create_at = 18;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.TokenInfo.prototype.getRefreshCreateAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 18));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
*/
proto.user.oauth.v1.TokenInfo.prototype.setRefreshCreateAt = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.clearRefreshCreateAt = function() {
  return this.setRefreshCreateAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.TokenInfo.prototype.hasRefreshCreateAt = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional int64 refresh_expires_in = 19;
 * @return {number}
 */
proto.user.oauth.v1.TokenInfo.prototype.getRefreshExpiresIn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setRefreshExpiresIn = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional string token_type = 20;
 * @return {string}
 */
proto.user.oauth.v1.TokenInfo.prototype.getTokenType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenInfo} returns this
 */
proto.user.oauth.v1.TokenInfo.prototype.setTokenType = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.ClientStore.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.ClientStore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.ClientStore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.ClientStore.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && gorm_types_types_pb.DeletedAt.toObject(includeInstance, f),
    secret: jspb.Message.getFieldWithDefault(msg, 5, ""),
    domain: jspb.Message.getFieldWithDefault(msg, 6, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.ClientStore}
 */
proto.user.oauth.v1.ClientStore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.ClientStore;
  return proto.user.oauth.v1.ClientStore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.ClientStore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.ClientStore}
 */
proto.user.oauth.v1.ClientStore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 4:
      var value = new gorm_types_types_pb.DeletedAt;
      reader.readMessage(value,gorm_types_types_pb.DeletedAt.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecret(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomain(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.ClientStore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.ClientStore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.ClientStore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.ClientStore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      gorm_types_types_pb.DeletedAt.serializeBinaryToWriter
    );
  }
  f = message.getSecret();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDomain();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional uint32 ID = 1;
 * @return {number}
 */
proto.user.oauth.v1.ClientStore.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.ClientStore} returns this
 */
proto.user.oauth.v1.ClientStore.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.ClientStore.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.ClientStore} returns this
*/
proto.user.oauth.v1.ClientStore.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.ClientStore} returns this
 */
proto.user.oauth.v1.ClientStore.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.ClientStore.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.user.oauth.v1.ClientStore.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.user.oauth.v1.ClientStore} returns this
*/
proto.user.oauth.v1.ClientStore.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.ClientStore} returns this
 */
proto.user.oauth.v1.ClientStore.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.ClientStore.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional types.DeletedAt deleted_at = 4;
 * @return {?proto.types.DeletedAt}
 */
proto.user.oauth.v1.ClientStore.prototype.getDeletedAt = function() {
  return /** @type{?proto.types.DeletedAt} */ (
    jspb.Message.getWrapperField(this, gorm_types_types_pb.DeletedAt, 4));
};


/**
 * @param {?proto.types.DeletedAt|undefined} value
 * @return {!proto.user.oauth.v1.ClientStore} returns this
*/
proto.user.oauth.v1.ClientStore.prototype.setDeletedAt = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.user.oauth.v1.ClientStore} returns this
 */
proto.user.oauth.v1.ClientStore.prototype.clearDeletedAt = function() {
  return this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.user.oauth.v1.ClientStore.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string secret = 5;
 * @return {string}
 */
proto.user.oauth.v1.ClientStore.prototype.getSecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.ClientStore} returns this
 */
proto.user.oauth.v1.ClientStore.prototype.setSecret = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string domain = 6;
 * @return {string}
 */
proto.user.oauth.v1.ClientStore.prototype.getDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.ClientStore} returns this
 */
proto.user.oauth.v1.ClientStore.prototype.setDomain = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string userID = 7;
 * @return {string}
 */
proto.user.oauth.v1.ClientStore.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.ClientStore} returns this
 */
proto.user.oauth.v1.ClientStore.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.user.oauth.v1.TokenGenerateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.user.oauth.v1.TokenGenerateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.TokenGenerateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    clientSecret: jspb.Message.getFieldWithDefault(msg, 2, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    redirecturi: jspb.Message.getFieldWithDefault(msg, 4, ""),
    scope: jspb.Message.getFieldWithDefault(msg, 5, ""),
    code: jspb.Message.getFieldWithDefault(msg, 6, ""),
    codeChallenge: jspb.Message.getFieldWithDefault(msg, 7, ""),
    codeChallengeMethod: jspb.Message.getFieldWithDefault(msg, 8, 0),
    refresh: jspb.Message.getFieldWithDefault(msg, 9, ""),
    codeVerifier: jspb.Message.getFieldWithDefault(msg, 10, ""),
    accessTokenExp: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.user.oauth.v1.TokenGenerateRequest}
 */
proto.user.oauth.v1.TokenGenerateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.user.oauth.v1.TokenGenerateRequest;
  return proto.user.oauth.v1.TokenGenerateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.user.oauth.v1.TokenGenerateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.user.oauth.v1.TokenGenerateRequest}
 */
proto.user.oauth.v1.TokenGenerateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientSecret(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirecturi(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setScope(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodeChallenge(value);
      break;
    case 8:
      var value = /** @type {!proto.user.oauth.v1.CodeChallengeMethod} */ (reader.readEnum());
      msg.setCodeChallengeMethod(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefresh(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodeVerifier(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAccessTokenExp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.user.oauth.v1.TokenGenerateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.user.oauth.v1.TokenGenerateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.user.oauth.v1.TokenGenerateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClientSecret();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRedirecturi();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getScope();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCodeChallenge();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCodeChallengeMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getRefresh();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCodeVerifier();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getAccessTokenExp();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
};


/**
 * optional string clientID = 1;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getClientid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setClientid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string client_secret = 2;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getClientSecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setClientSecret = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string userID = 3;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string redirectURI = 4;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getRedirecturi = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setRedirecturi = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string scope = 5;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getScope = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setScope = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string code = 6;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setCode = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string code_challenge = 7;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getCodeChallenge = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setCodeChallenge = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional CodeChallengeMethod code_challenge_method = 8;
 * @return {!proto.user.oauth.v1.CodeChallengeMethod}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getCodeChallengeMethod = function() {
  return /** @type {!proto.user.oauth.v1.CodeChallengeMethod} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.user.oauth.v1.CodeChallengeMethod} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setCodeChallengeMethod = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional string refresh = 9;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getRefresh = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setRefresh = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string code_verifier = 10;
 * @return {string}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getCodeVerifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setCodeVerifier = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional int64 access_token_exp = 11;
 * @return {number}
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.getAccessTokenExp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.user.oauth.v1.TokenGenerateRequest} returns this
 */
proto.user.oauth.v1.TokenGenerateRequest.prototype.setAccessTokenExp = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * @enum {number}
 */
proto.user.oauth.v1.ResponseType = {
  CODE: 0,
  TOKEN: 1
};

/**
 * @enum {number}
 */
proto.user.oauth.v1.CodeChallengeMethod = {
  PLAIN: 0,
  S256: 1
};

/**
 * @enum {number}
 */
proto.user.oauth.v1.GrantType = {
  AUTHORIZATION_CODE: 0,
  PASSWORD: 1,
  CLIENT_CREDENTIALS: 2,
  REFRESH_TOKEN: 3,
  __IMPLICIT: 4
};

goog.object.extend(exports, proto.user.oauth.v1);
