openapi: 3.0.3
info:
  title: empty_backend
  description: ''
  contact:
    name: yyue
    email: yy@yyue.dev
  license:
    name: ''
  version: 0.1.0
paths: {}
components:
  schemas:
    NewResource:
      type: object
      required:
      - resource_id
      - key
      - rtype
      - name
      - desc
      - sort
      - path
      - index
      - menu
      - icon
      properties:
        desc:
          type: string
        icon:
          type: string
        index:
          type: boolean
        key:
          type: string
        menu:
          type: boolean
        name:
          type: string
        path:
          type: string
        resource_id:
          type: integer
          format: int32
        rtype:
          type: integer
          format: int32
        sort:
          type: integer
          format: int32
    Resource:
      type: object
      required:
      - id
      - resource_id
      - key
      - rtype
      - name
      - desc
      - sort
      - path
      - index
      - menu
      - icon
      - created_at
      - updated_at
      properties:
        created_at:
          type: integer
          format: int64
        desc:
          type: string
        icon:
          type: string
        id:
          type: integer
          format: int32
        index:
          type: boolean
        key:
          type: string
        menu:
          type: boolean
        name:
          type: string
        path:
          type: string
        resource_id:
          type: integer
          format: int32
        rtype:
          type: integer
          format: int32
        sort:
          type: integer
          format: int32
        updated_at:
          type: integer
          format: int64
